# Generated by Django 4.2.3 on 2023-07-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.URLField(max_length=256)),
                ('short_url', models.CharField(max_length=7, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
