# Generated by Django 4.2.3 on 2023-07-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='visit_count',
        ),
    ]
